[children]
    Text(text: children_item)
[posts]
    PostItemComponent(title: title, body: body, integer: 54858, booly: true, user: user)
    [tags]
        Text(text: tags_item)
    !fuckface
        Text(text: "fuckface")
    user
        Text(text: name)
![posts]
    Text(text: "no posts found")
currentUser
    Text(text: "current user set!")
!currentUser
    Text(text: "no user set!")
    currentUser
        Text(text: "fin")
FooterComponent()
realUser.name
    Text(text: "shit")
fuck
    Text(text: "dong", values: [realUser.name], nums:[324324,32434,1111])
[realUser.aliases]
    Text(text: aliases_item)
![realUser.aliases]
    Text(text: "BMANSLIP!")
!boolTest
    Text(text: "BOOL TEST FALSE")
[posts]
    PostComponent(post: posts_item)
